# Generated by Django 4.1.7 on 2023-02-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_code_postal_commande_numéro_téléphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='600', max_length=200),
            preserve_default=False,
        ),
    ]
