# Generated by Django 4.1.7 on 2023-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Quartier',
            field=models.CharField(default='500', max_length=200),
            preserve_default=False,
        ),
    ]
